const express = require('express'); // this is the Express framework for Node.js, which is a popular web application framework that provides a robust set of features for building web applications
const http = require('http'); // this is the built-in http module in Node.js
const socketio = require('socket.io'); // this is the Socket.IO library for Node.js, which is a 3rd party library that needs to be installed via npm
const app = express(); // this creates an instance of the Express application
console.log(__dirname); // this logs the current directory path to the console, which is useful for debugging and understanding where the server is running
app.use(express.static(__dirname + '\\public')); // this serves static files from the 'public' directory, which means that any files in that directory can be accessed via the web server
const express_server = app.listen(8000, () => { // this starts the Express server and listens on port 8080
  console.log('Express server is listening on port 8000');
});
const io = socketio(express_server); // this creates a Socket.IO server that shares the same HTTP server as the Express application
io.on('connection', (socket) => { // this event is triggered when a new Socket.IO connection is established
  console.log('A new client has connected'); 
  console.log(socket.id, "has connected."); // this logs the unique id of the socket, which is generated by the server when the connection is established
  // in websocket we use send and on to send and receive messages, in socket.io we use emit and on to send and receive messages.
  socket.emit('messageFromServer', {data: 'welcom to the socket server.'}); // this sends a welcome message to the client that just connected
  socket.on('messageFromClient', (data) => { // this event is triggered when the server receives a message from the client
    console.log('Message from client:', data); // this logs the message received from the client to the console
  });
});